### ISSUE TITLE
Customise css issue

### ISSUE THREAD

**Issue by ChukkaAshok** [ittus/vue-monthly-picker#18]
how can i change **date-popover**  style,
Please help me any one.

**Comment by ittus** [comment]
This component will have class name `vue-monthly-picker`. If you're using less or scss, you can use [deep selector ](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements) to set style for `date-popover`

For example:
```scss
<style lang="scss">
.vue-monthly-picker {
  /deep/ .date-popover {
    background-color: black !important;
    color: white;
  }
}
</style>
```
